### ISSUE TITLE
Running pod-configuration as non-root user with chmod 

### ISSUE THREAD

**Issue by dungeonhao** [oceanprotocol/pod-configuration#47]
OpenShift by default run containers as a non root user. If we're going to run the c2d components on openshift, we would not be able to utilised the chmod (chmodSync) 777 command

https://github.com/oceanprotocol/pod-configuration/blob/59bcf19220df4dcd9990d426e4eb6409c6671f01/src/index.js#L52

Would love for the command to be env variable if provided, something like this
```
    fs.chownSync(inputsDir, process.env.USER_ID, process.env.USER_ID)
```

**Comment by LoznianuAnamaria** [comment]
This needs to be done on all ocean repos. The issue will be tracked here: https://github.com/oceanprotocol/s1-dapps/issues/76
