### ISSUE TITLE
env variable to control timeout

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/pod-configuration#53]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mihaisc** [comment]
@alexcos20 @mariacarmina status on this? can we close it?

**Comment by mariacarmina** [comment]
> @alexcos20 @mariacarmina status on this? can we close it?

I think it can be closed as far as I know. The timeout wasn't an issue for pod-configuration.
